"""
Pydantic models for dataset entries and generated replies.
Shared across data generation, reply generation, and evaluation.
"""

from pydantic import BaseModel, Field


class EmailScenario(BaseModel):
    """A customer email scenario with gold-standard reference reply."""

    id: str = Field(description="Unique identifier, e.g. 'email_001'")
    subject: str = Field(description="Email subject line")
    customer_email_body: str = Field(description="The customer's actual email text")
    category: str = Field(
        description="One of: billing, bug_report, refund_request, "
        "feature_question, cancellation, complaint"
    )
    sentiment: str = Field(
        description="One of: angry, neutral, confused, happy"
    )
    urgency: str = Field(description="One of: low, medium, high")
    prior_thread_summary: str | None = Field(
        default=None,
        description="Prior conversation context (null for cold emails)",
    )
    reference_reply: str = Field(
        description="Gold-standard reply — what a human agent would send"
    )
    reference_reply_key_points: list[str] = Field(
        description="Key factual/action points from the reference reply"
    )
    ideal_reply_traits: list[str] = Field(
        description="Abstract quality expectations for a good reply"
    )


class GeneratedReply(BaseModel):
    """A reply generated by the AI system for evaluation."""

    id: str = Field(description="Matches the EmailScenario id")
    reply_subject: str = Field(description="Reply email subject")
    reply_body: str = Field(description="The generated reply text")
    tone_used: str = Field(
        description="e.g. 'empathetic', 'professional', 'concise'"
    )
    suggested_next_action: str = Field(
        description="What should happen next"
    )
    confidence: float = Field(
        ge=0.0, le=1.0, description="Confidence score 0.0–1.0"
    )


class DimensionScore(BaseModel):
    """Score for a single evaluation dimension."""

    value: float = Field(ge=0.0, le=10.0, description="Score 0–10")
    method: str = Field(
        description="'llm_judge' | 'deterministic' | 'reference_compare'"
    )
    justification: str = Field(
        default="", description="For LLM-judged dimensions"
    )
    detail: str = Field(
        default="", description="For deterministic dimensions"
    )


class ResponseEvaluation(BaseModel):
    """Complete evaluation of a single generated reply."""

    id: str
    scores: dict[str, DimensionScore]
    composite_score: float = Field(ge=0.0, le=10.0)
    flags: list[str] = Field(
        default_factory=list,
        description="e.g. ['hallucination_risk', 'low_relevance']",
    )


class DimensionStats(BaseModel):
    """Aggregate statistics for a single dimension across all responses."""

    mean: float
    median: float
    min: float
    max: float
    std_dev: float


class AggregateReport(BaseModel):
    """Overall evaluation report across all responses."""

    dimension_stats: dict[str, DimensionStats]
    overall_composite_mean: float
    overall_composite_median: float
    worst_performing_category: str
    best_performing_category: str
    systemic_issues: list[str]
    total_evaluated: int
    total_failed: int
